smalltalk.addPackage('GitHubPage', {});
smalltalk.addClass('GitHubPage', smalltalk.Widget, ['username', 'repositoryDiv', 'userInfo'], 'GitHubPage');
smalltalk.addMethod(
unescape('_renderOn_'),
smalltalk.method({
selector: unescape('renderOn%3A'),
fn: function (html){
var self=this;
(function($rec){smalltalk.send($rec, "_class_", ["container"]);return smalltalk.send($rec, "_with_", [(function(){smalltalk.send(self, "_renderBodyOn_", [html]);smalltalk.send(self, "_renderRepositoryHeading_", [html]);(self['@repositoryDiv']=smalltalk.send(smalltalk.send(html, "_div", []), "_id_", ["repos"]));smalltalk.send(self, "_getRepositories", []);return smalltalk.send(self, "_initializeMasonry", []);})]);})(smalltalk.send(html, "_div", []));
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_username'),
smalltalk.method({
selector: unescape('username'),
fn: function (){
var self=this;
return self['@username'];
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_username_'),
smalltalk.method({
selector: unescape('username%3A'),
fn: function (aString){
var self=this;
(self['@username']=aString);
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_sampleRepositoryResponse'),
smalltalk.method({
selector: unescape('sampleRepositoryResponse'),
fn: function (){
var self=this;
unescape("%0A%20%20%7B%0A%20%20%20%20%22git_url%22%3A%20%22git%3A//github.com/dalehenrich/smallsource.git%22%2C%0A%20%20%20%20%22ssh_url%22%3A%20%22git@github.com%3Adalehenrich/smallsource.git%22%2C%0A%20%20%20%20%22mirror_url%22%3A%20null%2C%0A%20%20%20%20%22url%22%3A%20%22https%3A//api.github.com/repos/dalehenrich/smallsource%22%2C%0A%20%20%20%20%22has_downloads%22%3A%20true%2C%0A%20%20%20%20%22created_at%22%3A%20%222012-01-30T18%3A02%3A07Z%22%2C%0A%20%20%20%20%22has_issues%22%3A%20false%2C%0A%20%20%20%20%22master_branch%22%3A%20null%2C%0A%20%20%20%20%22description%22%3A%20%22Smalltalk%20source%20files%22%2C%0A%20%20%20%20%22forks%22%3A%200%2C%0A%20%20%20%20%22svn_url%22%3A%20%22https%3A//github.com/dalehenrich/smallsource%22%2C%0A%20%20%20%20%22html_url%22%3A%20%22https%3A//github.com/dalehenrich/smallsource%22%2C%0A%20%20%20%20%22fork%22%3A%20true%2C%0A%20%20%20%20%22has_wiki%22%3A%20true%2C%0A%20%20%20%20%22private%22%3A%20false%2C%0A%20%20%20%20%22clone_url%22%3A%20%22https%3A//github.com/dalehenrich/smallsource.git%22%2C%0A%20%20%20%20%22homepage%22%3A%20%22%22%2C%0A%20%20%20%20%22size%22%3A%20128%2C%0A%20%20%20%20%22open_issues%22%3A%200%2C%0A%20%20%20%20%22updated_at%22%3A%20%222012-03-01T16%3A36%3A38Z%22%2C%0A%20%20%20%20%22owner%22%3A%20%7B%0A%20%20%20%20%20%20%22url%22%3A%20%22https%3A//api.github.com/users/dalehenrich%22%2C%0A%20%20%20%20%20%20%22gravatar_id%22%3A%20%225d423de04ebac0b8f9412a9a381c9460%22%2C%0A%20%20%20%20%20%20%22login%22%3A%20%22dalehenrich%22%2C%0A%20%20%20%20%20%20%22avatar_url%22%3A%20%22https%3A//secure.gravatar.com/avatar/5d423de04ebac0b8f9412a9a381c9460%3Fd%3Dhttps%3A//a248.e.akamai.net/assets.github.com%252Fimages%252Fgravatars%252Fgravatar-140.png%22%2C%0A%20%20%20%20%20%20%22id%22%3A%20623951%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22name%22%3A%20%22smallsource%22%2C%0A%20%20%20%20%22watchers%22%3A%202%2C%0A%20%20%20%20%22pushed_at%22%3A%20%222012-01-31T23%3A28%3A34Z%22%2C%0A%20%20%20%20%22id%22%3A%203307281%2C%0A%20%20%20%20%22language%22%3A%20null%0A%20%20%7D%2C%0A");
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_renderBodyOn_'),
smalltalk.method({
selector: unescape('renderBodyOn%3A'),
fn: function (html){
var self=this;
smalltalk.send(html, "_h1_", [unescape("Dale%20Henrich%27s%20GitHub%20Repositories")]);
smalltalk.send(smalltalk.send(html, "_p", []), "_with_", [(function(h){smalltalk.send(h, "_with_", [unescape("Hi%20there%2C%20world.%20This%20page%20is%20powered%20by%20")]);(function($rec){smalltalk.send($rec, "_href_", [unescape("http%3A//amber-lang.net/")]);return smalltalk.send($rec, "_with_", ["Amber Smalltalk"]);})(smalltalk.send(h, "_a", []));return smalltalk.send(h, "_with_", ["."]);})]);
smalltalk.send(smalltalk.send(html, "_p", []), "_with_", [(function(h){smalltalk.send(h, "_with_", [unescape("If%20you%27re%20new%20to%20Smalltalk%2C%20take%20an%20")]);(function($rec){smalltalk.send($rec, "_href_", [unescape("amber/learn.html")]);return smalltalk.send($rec, "_with_", [unescape("Amber-powered%20Smaltalk%20tutorial")]);})(smalltalk.send(h, "_a", []));return smalltalk.send(h, "_with_", [unescape("%20right%20in%20your%20own%20browser%21")]);})]);
smalltalk.send(smalltalk.send(html, "_p", []), "_with_", [(function(h){smalltalk.send(h, "_with_", ["The list of repositories below is generated by making calls to the"]);(function($rec){smalltalk.send($rec, "_href_", [unescape("http%3A//developer.github.com/")]);return smalltalk.send($rec, "_with_", [" GitHub development API"]);})(smalltalk.send(h, "_a", []));return smalltalk.send(h, "_with_", [" from Amber Smalltalk."]);})]);
smalltalk.send(smalltalk.send(html, "_p", []), "_with_", [(function(h){smalltalk.send(h, "_with_", ["If you want to see how this is done: "]);(function($rec){smalltalk.send($rec, "_with_", [smalltalk.send(smalltalk.send("Browse the ", "__comma", [smalltalk.send(smalltalk.send(self, "_class", []), "_name", [])]), "__comma", [" class"])]);return smalltalk.send($rec, "_onClick_", [(function(){return smalltalk.send((smalltalk.Browser || Browser), "_openOn_", [smalltalk.send(self, "_class", [])]);})]);})(smalltalk.send(h, "_button", []));smalltalk.send(h, "_with_", [" and "]);(function($rec){smalltalk.send($rec, "_href_", [smalltalk.send(smalltalk.send(smalltalk.send(smalltalk.send(unescape("https%3A//github.com/"), "__comma", [smalltalk.send(self, "_username", [])]), "__comma", [unescape("/")]), "__comma", [smalltalk.send(self, "_username", [])]), "__comma", [".github.com"])]);return smalltalk.send($rec, "_with_", ["visit the github repository"]);})(smalltalk.send(h, "_a", []));return smalltalk.send(h, "_with_", ["."]);})]);
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_renderRepositoryData_'),
smalltalk.method({
selector: unescape('renderRepositoryData%3A'),
fn: function (repositoryData){
var self=this;
var homepage=nil;
var sortedData=nil;
(sortedData=smalltalk.send(smalltalk.send(repositoryData, "_asArray", []), "_sort_", [(function(a, b){return ((($receiver = smalltalk.send(smalltalk.send(a, "_name", []), "_asUppercase", [])).klass === smalltalk.Number) ? $receiver <=smalltalk.send(smalltalk.send(b, "_name", []), "_asUppercase", []) : smalltalk.send($receiver, "__lt_eq", [smalltalk.send(smalltalk.send(b, "_name", []), "_asUppercase", [])]));})]));
smalltalk.send(self['@repositoryDiv'], "_contents_", [(function(html){smalltalk.send(sortedData, "_do_", [(function(repo){return (function($rec){smalltalk.send($rec, "_class_", ["four columns repo"]);return smalltalk.send($rec, "_with_", [(function(){smalltalk.send(smalltalk.send(html, "_h4", []), "_with_", [(function(){return (function($rec){smalltalk.send($rec, "_href_", [smalltalk.send(repo, "_at_", ["html_url"])]);return smalltalk.send($rec, "_with_", [smalltalk.send(repo, "_name", [])]);})(smalltalk.send(html, "_a", []));})]);smalltalk.send(html, "_p_", [smalltalk.send(repo, "_description", [])]);return smalltalk.send((homepage=smalltalk.send(repo, "_homepage", [])), "_ifNotEmpty_", [(function(){return (function($rec){smalltalk.send($rec, "_href_", [homepage]);return smalltalk.send($rec, "_with_", [homepage]);})(smalltalk.send(html, "_a", []));})]);})]);})(smalltalk.send(html, "_div", []));})]);return smalltalk.send(self, "_reloadMasonry", []);})]);
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_renderRepositoryError_'),
smalltalk.method({
selector: unescape('renderRepositoryError%3A'),
fn: function (aString){
var self=this;
smalltalk.send(self['@repositoryDiv'], "_with_", [aString]);
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_getRepositories'),
smalltalk.method({
selector: unescape('getRepositories'),
fn: function (){
var self=this;
smalltalk.send((typeof jQuery == 'undefined' ? nil : jQuery), "_ajax_options_", [smalltalk.send(self, "_repoUrl", []), smalltalk.HashedCollection._fromPairs_([smalltalk.send("type", "__minus_gt", ["GET"]),smalltalk.send("dataType", "__minus_gt", ["jsonp"]),smalltalk.send("success", "__minus_gt", [(function(repositoryData, status, jqXHR){return smalltalk.send(self, "_renderRepositoryData_", [smalltalk.send(repositoryData, "_data", [])]);})]),smalltalk.send("error", "__minus_gt", [(function(jqXHR, status, error){return smalltalk.send(self, "_renderRepositoryError_", [smalltalk.send(status, "_printString", [])]);})])])]);
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_getUserInfo'),
smalltalk.method({
selector: unescape('getUserInfo'),
fn: function (){
var self=this;
try{smalltalk.send((typeof jQuery == 'undefined' ? nil : jQuery), "_ajax_options_", [smalltalk.send(self, "_userInfoUrl", []), smalltalk.HashedCollection._fromPairs_([smalltalk.send("type", "__minus_gt", ["GET"]),smalltalk.send("dataType", "__minus_gt", ["jsonp"]),smalltalk.send("success", "__minus_gt", [(function(repositoryData, status, jqXHR){return (function(){throw({name: 'stReturn', selector: '_getUserInfo', fn: function(){return smalltalk.send(smalltalk.send(repositoryData, "_data", []), "_at_", ["name"])}})})();})]),smalltalk.send("error", "__minus_gt", [(function(jqXHR, status, error){return (function(){throw({name: 'stReturn', selector: '_getUserInfo', fn: function(){return "error getting your name.  check your username"}})})();})])])]);
return self;
} catch(e) {if(e.name === 'stReturn' && e.selector === '_getUserInfo'){return e.fn()} throw(e)}}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_apiUrl'),
smalltalk.method({
selector: unescape('apiUrl'),
fn: function (){
var self=this;
return unescape("https%3A//api.github.com");
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_repoUrl'),
smalltalk.method({
selector: unescape('repoUrl'),
fn: function (){
var self=this;
return smalltalk.send(smalltalk.send(self, "_userInfoUrl", []), "__comma", [unescape("/repos")]);
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_userInfoUrl'),
smalltalk.method({
selector: unescape('userInfoUrl'),
fn: function (){
var self=this;
return smalltalk.send(smalltalk.send(smalltalk.send(self, "_apiUrl", []), "__comma", [unescape("/users/")]), "__comma", [smalltalk.send(self, "_username", [])]);
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_renderUserData_'),
smalltalk.method({
selector: unescape('renderUserData%3A'),
fn: function (repositoryData){
var self=this;
smalltalk.send((typeof headline == 'undefined' ? nil : headline), "_contents_", [(function(html){return smalltalk.send(smalltalk.send(html, "_h1", []), "_with_at_", [repositoryData, "name"]);})]);
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_renderRepositoryHeading_'),
smalltalk.method({
selector: unescape('renderRepositoryHeading%3A'),
fn: function (html){
var self=this;
(function($rec){smalltalk.send($rec, "_class_", ["row"]);return smalltalk.send($rec, "_with_", [(function(){(function($rec){smalltalk.send($rec, "_class_", ["eight columns alpha"]);return smalltalk.send($rec, "_with_", [(function(){return smalltalk.send(html, "_h2_", ["Repositories"]);})]);})(smalltalk.send(html, "_div", []));return smalltalk.send(smalltalk.send(html, "_div", []), "_with_", [(function(){return (function($rec){smalltalk.send($rec, "_class_", ["refresh"]);smalltalk.send($rec, "_with_", ["Refresh repository list"]);return smalltalk.send($rec, "_onClick_", [(function(){return smalltalk.send(self['@repositoryDiv'], "_contents_", [(function(div){return smalltalk.send(self, "_getRepositories", []);})]);})]);})(smalltalk.send(html, "_button", []));})]);})]);})(smalltalk.send(html, "_div", []));
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_runMasonry'),
smalltalk.method({
selector: unescape('runMasonry'),
fn: function (){
var self=this;
$('#repos').masonry({itemSelector:'.repo' , columnWidth:10});
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_initializeMasonry'),
smalltalk.method({
selector: unescape('initializeMasonry'),
fn: function (){
var self=this;
$('#repos').masonry({itemSelector:'.repo' , columnWidth:1});
return self;}
}),
smalltalk.GitHubPage);

smalltalk.addMethod(
unescape('_reloadMasonry'),
smalltalk.method({
selector: unescape('reloadMasonry'),
fn: function (){
var self=this;
$('#repos').masonry('reload');
return self;}
}),
smalltalk.GitHubPage);


smalltalk.addMethod(
unescape('_openOn_'),
smalltalk.method({
selector: unescape('openOn%3A'),
fn: function (aString){
var self=this;
(function($rec){smalltalk.send($rec, "_username_", [aString]);return smalltalk.send($rec, "_appendToJQuery_", [smalltalk.send("body", "_asJQuery", [])]);})(smalltalk.send(self, "_new", []));
return self;}
}),
smalltalk.GitHubPage.klass);


